// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbSt8PvswbfUbAsX1gWecIHEAzpQ5Rx6k',
    appId: '1:323115104602:web:2ad3d9716e4e608fbe1b63',
    messagingSenderId: '323115104602',
    projectId: 'whisperwaves-bbc35',
    authDomain: 'whisperwaves-bbc35.firebaseapp.com',
    storageBucket: 'whisperwaves-bbc35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfufyeip-XwLMCNkAUO95bIwSuypMtG5g',
    appId: '1:323115104602:android:b99f0cbecfea09d4be1b63',
    messagingSenderId: '323115104602',
    projectId: 'whisperwaves-bbc35',
    storageBucket: 'whisperwaves-bbc35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBskjmmlq5L9Y-_Me26Q8WEnYr_jhQ0Dvg',
    appId: '1:323115104602:ios:1a3ab58d898630e5be1b63',
    messagingSenderId: '323115104602',
    projectId: 'whisperwaves-bbc35',
    storageBucket: 'whisperwaves-bbc35.appspot.com',
    iosBundleId: 'com.bananakin.chatSmth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBskjmmlq5L9Y-_Me26Q8WEnYr_jhQ0Dvg',
    appId: '1:323115104602:ios:66157c0963c9311bbe1b63',
    messagingSenderId: '323115104602',
    projectId: 'whisperwaves-bbc35',
    storageBucket: 'whisperwaves-bbc35.appspot.com',
    iosBundleId: 'com.bananakin.chatSmth.RunnerTests',
  );
}
